import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import * as React from "react";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Link href="/spaces">
          <a>spaces</a>
        </Link>
      </div>
    </div>
  );
};

export default Home;
